### ISSUE TITLE
Generate a permalink for sharing the visualizer view of some schema.org markup

### ISSUE THREAD

**Issue by rtroncy** [pasqLisena/schema-visualizer#1]
Simple idea: the idea is that once I'm satisfied with some edited json-ld and the rendered view, I would like to share the view with a permalink. I would like to avoid super long URI. Hashing (and reverse hashing) is a possibility. Storing them in a db is another possibility.

**Comment by pasqLisena** [comment]
Reverse hashing is possible? I am not able to find any way to do it...

I am also considering to have a long url with everything and minifying it with tinyurl or something like this (if they expose apis)

**Comment by rtroncy** [comment]
Look at what we do in 3cixty with bookmarks. I'm sharing with you this [bookmak](https://nice.3cixty.com/#bookmark=7h4E4SZRLfOJZX55NO66dGDwuLPFZrti-7) and I know that by clicking on them, you will exactly recreate my navigation path, i.e. I have selected a place in Nice (Château de Nice) and events happening nearby within 300 meters, and select the "Axe Boat Festival" that is happening now :-). I'm suggesting you implement a similar feature.

How to do it? You can just discuss with https://github.com/Kai-Dominik and https://github.com/spirescu who implement it, directly on the 3cixty slack channel (you have been invited)

**Comment by pasqLisena** [comment]
Yes Raphael, the feature to implement was clear 😄 

I am thinking about how to implement it client-side, so without a db... But maybe set up a little db could be the best option

**Comment by rtroncy** [comment]
Ah, right, client-side only might indeed be tricky! I also don't know exactly how is the 3cixty bookmarks db schema made, I should ask.

**Comment by pasqLisena** [comment]
The feature is online.

I used [mLab](https://mlab.com/home) that is a service that exposes a MongoDB through apis (we should fit in the free quota).

So basically the json is sent to the db, that gives us back the id for asking it back again.

**Comment by rtroncy** [comment]
Cool. So, if one submit exactly the same json, the same id will be sent back? I imagine that the key ion the db is a hash of the json input, right?

I suggest you update the README in order to further document this feature, mentioning mLab and the quota we have. This means that 'some' credentials (for connecting to mLab) are also in the code?

**Comment by pasqLisena** [comment]
> Cool. So, if one submit exactly the same json, the same id will be sent back? I imagine that the key ion the db is a hash of the json input, right?

Actually not. If we need, I can pre-compute the id (hashing the json) before the call to the APIs.

> This means that 'some' credentials (for connecting to mLab) are also in the code?

Yes, the API key.

**Comment by rtroncy** [comment]
No need to pre-compute the id, this will anyway be too sensitive. One can just add a newline or a whitespace in the json to get a different input string while being semantically equivalent.

Document in the README this dependency and how one should input its own key, otherwise, if this repo get popular and cloned / forked, your db will be a mess
